<?php

/**
 * @file
 *   Basic module to provide access and storage of bit.ly shortened URLs.
 */

/**
 * Implementation of hook_help().
 */
function bitly_help($path, $arg) {
  switch ($path) {
    case "admin/help#shorten":
      return '<p>'. t("This module provides a framework for other Drupal " .
                      "modules to shorten URLs and display statistics using " .
                      "the bit.ly service.") .'</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function bitly_menu() {
  $items = array();
  $items['admin/settings/bitly'] = array(
    'title' => 'Bit.ly',
    'description' => 'Provide global options for the bit.ly module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bitly_admin'),
    'access arguments' => array('access administration pages'),
  );
  $items['bitly_oauth'] = array(
    'title' => 'Validate bit.ly credentials',
    'page callback' => '_bitly_oauth',
    'access arguments' => array('use own bit.ly login'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function bitly_perm() {
  return array('use own bit.ly login', 'use bit.ly');
}

/**
 * Admin settings page.
 */
function bitly_admin($form_state) {
  $form['bitly_keys'] = array(
    '#type' => 'fieldset',
    '#title' => t('Bit.ly API Credentials'),
    '#description' => t('Please supply the bit.ly API credentials that will be used globally. These API credentials will be used in any case where a user either does not or cannot supply their own credentials. !here.', array('!here' => l('Find your credentials', 'http://bit.ly/a/your_api_key'))),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['bitly_keys']['bitly_login'] = array(
    '#type' => 'textfield',
    '#title' => t('Bit.ly Login'),
    '#required' => TRUE,
    '#default_value' => variable_get('bitly_login', ''),
    '#description' => t('This field is case-sensitive.'),
  );
  $form['bitly_keys']['bitly_key'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Bit.ly API Key'),
    '#default_value' => variable_get('bitly_key', ''),
    '#description' => t('This field is case-sensitive.'),
  );
  $form['bitly_oauth'] = array(
    '#type' => 'fieldset',
    '#title' => t('Bit.ly OAuth Credentials'),
    '#description' => t('Please supply OAuth to allow users to log into their bit.ly accounts by clicking a sign-in link rather than needing to enter an API key. Currently you must !request directly from bit.ly.', array('!request' => l('request OAuth access', 'http://code.google.com/p/bitly-api/wiki/ApiDocumentation#OAuth'))),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['bitly_oauth']['bitly_client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Bit.ly OAuth client_id'),
    '#default_value' => variable_get('bitly_client_id', ''),
    '#description' => t('This field is case-sensitive.'),
  );
  $form['bitly_oauth']['bitly_client_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Bit.ly OAuth client_secret'),
    '#default_value' => variable_get('bitly_client_secret', ''),
    '#description' => t('This field is case-sensitive.'),
  );
  $form['bitly_oauth']['bitly_oauth_test'] = array(
    '#value' => t('!test', array('!test' => l('Test OAuth', 'bitly_oauth')))
  );

  return system_settings_form($form);
}

/**
 * Handles user OAuth interaction.
 */
function _bitly_oauth() {
  global $user;
  $client_id = variable_get('bitly_client_id', '');
  global $base_root;
  $redirect_uri = $base_root . base_path() . 'bitly_oauth';
  if(empty($_REQUEST['code'])) {
    drupal_goto("https://bit.ly/oauth/authorize?client_id=$client_id&redirect_uri=$redirect_uri");
  }
  else {
    _bitly_inc();
    $results = bitly_oauth_access_token($_REQUEST['code'], $redirect_uri);
    if(!empty($results)) {
      $array = array(
        'uid' => $user->uid,
        'login' => $results['login'],
        'token' => $results['access_token'],
        'key' => $results['apiKey'],
      );
      $error = drupal_write_record('bitly_auth', $array);
      print_r($error);
    }
  }
  
}

/**
 * Helper function to create proper defines before loading bitly.inc.
 */
function _bitly_inc() {
  define('bitlyKey', variable_get('bitly_key', ''));
  define('bitlyLogin', variable_get('bitly_login', ''));
  define('bitly_clientid', variable_get('bitly_client_id', ''));
  define('bitly_secret', variable_get('bitly_client_secret', ''));
  module_load_include('inc', 'bitly');
}